---
title: "R Camp 2022 Winter"
format: revealjs
editor: visual
execute: 
  echo: false
---

## Number of NGS test at CMC Seoul

```{r}
library(tidyverse)

mutation <- readr::read_csv(here::here("data/Pathology_NGS_mutation.csv"))
clinical <- readr::read_csv(here::here("data/Pathology_NGS_1st.csv"))

library(lubridate)

clinicalDate <- clinical |>
  mutate(prescription_date = ymd(prescription_date),
         year = lubridate::year(prescription_date),
         month = lubridate::month(prescription_date),
         year_month = floor_date(prescription_date, "1 month"))

clinicalDate |>
  filter(year_month > "2020-10-01") |>
  ggplot2::ggplot(aes(x=year_month)) +
  #geom_bar()+
  geom_line(stat = "count")+
  xlab("Year (Monthly)")+
  ylab("Number of NGS test \n (ThermoFisher)")+
  theme_minimal()
```

## Number of NGS test by Cancer Types

```{r}

clinicalTumorType <- clinicalDate |>
  mutate(tumor_type = as.factor(tumor_type))


clinicalTumorType <- clinicalDate |>
  mutate(tumor_type = as.factor(tumor_type),
         tumor_type = str_to_lower(tumor_type),
         cancer_type = case_when(str_detect(tumor_type, "colo|rectal") ~ "Colorectal Cancer",
                                 str_detect(tumor_type, "lung") ~ "Lung Cancer",
                                 str_detect(tumor_type, "glioblastoma|glioma|ependymoma|astrocytoma") ~ "Brain Cancer",
                                 str_detect(tumor_type, "pancrea") ~ "Pancreas Cancer",
                                 str_detect(tumor_type, "gastric") ~ "Stomach Cancer",
                                 str_detect(tumor_type, "breast") ~ "Breast Cancer",
                                 is.na(tumor_type) ~ NA_character_,
                                 TRUE ~ "Other Cancer"),
         cancer_type = as.factor(cancer_type))

clinicalTumorType |>
  filter(year_month > "2020-10-01") |>
  ggplot2::ggplot(aes(x=year_month)) + #, color = cancer_type)) +
  #geom_bar()+
  geom_bar(stat = "count")+
  facet_wrap(vars(cancer_type), ncol = 3)+
  xlab("Year (Monthly)")+
  ylab("Number of NGS test \n (ThermoFisher)")+
  theme_minimal()
```

---

```{r}
load(here::here("RData/dfNested.RData"))

chisq <- dfNested |>
  mutate(msi_chisq = map(data, ~ chisq.test(.x$cancer_type, .x$nucleotide_change)),
         tidy_chisq = map(msi_chisq, broom::tidy))|>
  unnest(tidy_chisq)

chisq |>
  #arrange(p.value)|>
  #mutate(gene = as.factor(gene),
  #       gene = fct_inorder(gene)) |>
  mutate(significantGene = factor(p.value < 10^-3)) |>
  ggplot(aes(fct_reorder(gene, p.value), -log(p.value, base = 10))) +
  geom_bar(stat = "identity") +
  coord_flip()+
  theme(axis.text.y=element_text(size = rel(0.6)))+
  labs(title = "Differently mutated genes among cancer types",
       subtitle = "Chi-square test",
       x = "",
       y = "Minus log 10 transformed p value")

```

---

```{r}

msi_t.test <- dfNested |>
  unnest()|>
  #ungroup()|>
  mutate(log_msi = log1p(msiscore_number))|>
  group_by(gene)|>
  nest()|>
  mutate(msi_t.test = map(data, ~ t.test(log_msi ~ nucleotide_change,
                                         data = .x)),
         tidy_t.test = map(msi_t.test, broom::tidy)) |>
         #gene = fct_reorder(gene, p.value))|>
  unnest(tidy_t.test)

msi_t.test |>
  mutate(significantGene = factor(p.value < 10^-2)) |>
  ggplot(aes(estimate, -log(p.value, base = 10), label = gene, col = significantGene)) +
  #geom_point() +
  geom_text(size = 2.0)+
  labs(title = "MSI score difference related genes",
       subtitle = "T test",
       x = "Difference",
       y = "Minus log 10 transformed p value")
```

